### ISSUE TITLE
Commands for keyboard keys

### ISSUE THREAD

**Issue by Jakarrrg** [guinuxbr/KDEConnect-commands#2]
Hello, I am trying to find a command for sending a single specific keystroke from smartphone to PC. For example the spacebar key would be usefull since it is used to pause/unpause media in most players, or the right/left arrows to fast forward, and i would like having a simple command for spacebar lets say on my quick commands menu and not having to open the kde app and navigate to input and keyboard. If you could help i would be very thankfull.

**Comment by guinuxbr** [comment]
You have to grant KDE Connect this permission to control your media player. It is built-in functionality.
https://userbase.kde.org/KDEConnect#Multimedia_Control_Receiver
